In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv(r"D:\Geethanjaliexternship\Project\Flask\car performance-dataset.csv")

In [3]:
data.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino

In [4]:
data.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

In [5]:
x = data.iloc[:,1:8].values
y = data.iloc[:,0].values

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
x_train = sd.fit_transform(x_train)
x_test = sd.transform(x_test)

In [8]:
x_train

array([[ 1.49526939,  1.22961301,  1.24359144, ..., -0.79520768,
        -1.13752513, -0.73301171],
       [-0.85285735, -0.92367663, -1.16092059, ...,  1.24411524,
        -1.41177304,  0.5068698 ],
       [-0.85285735, -0.92367663, -0.68001818, ...,  0.05760009,
         1.05645814,  0.5068698 ],
       ...,
       [-0.85285735, -1.206235  , -1.45480539, ...,  1.42950823,
        -0.86327722,  0.5068698 ],
       [ 0.32120602,  0.56706235, -0.09224857, ..., -0.2390287 ,
        -1.41177304, -0.73301171],
       [-0.85285735, -0.99188037, -0.86703579, ...,  0.31715028,
        -0.31478141,  0.5068698 ]])

In [9]:
x_test

array([[ 1.49526939e+00,  1.55114495e+00,  1.32374184e+00,
         1.38121932e+00, -9.80600673e-01, -1.13752513e+00,
        -7.33011713e-01],
       [-8.52857354e-01, -5.04710772e-01, -7.60168584e-01,
        -4.99341807e-01,  5.02543270e-01, -5.89029314e-01,
        -7.33011713e-01],
       [ 1.49526939e+00,  1.07371874e+00,  9.76423440e-01,
         1.57674079e+00,  1.31757284e-01, -1.13752513e+00,
        -7.33011713e-01],
       [-8.52857354e-01, -6.99578613e-01, -4.39566980e-01,
         1.84938650e-02,  1.42950823e+00, -1.13752513e+00,
         5.06869802e-01],
       [ 3.21206016e-01,  3.91681296e-01, -9.22485749e-02,
         3.84652269e-01, -5.36357086e-02, -1.41177304e+00,
        -7.33011713e-01],
       [-8.52857354e-01, -1.16726143e+00, -9.20469386e-01,
        -1.60018698e+00,  8.73329255e-01, -1.41177304e+00,
         1.74675132e+00],
       [-8.52857354e-01, -1.03085394e+00, -1.02733659e+00,
        -1.17122470e+00, -1.64871504e-01,  7.82210231e-01,
         1.7467513

In [10]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor (n_estimators = 10 ,random_state = 0)
rf.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [11]:
y_pred = rf.predict(x_test)
y_pred

array([14.6 , 24.61, 14.2 , 20.  , 18.1 , 30.5 , 35.59, 21.25, 15.1 ,
       26.79, 37.72, 37.72, 18.5 , 28.43, 16.75, 33.17, 28.22, 27.02,
       17.1 , 35.78, 15.95, 22.3 , 23.24, 20.55, 31.9 , 28.87, 30.85,
       29.61, 31.94, 16.3 , 19.04, 34.14, 19.61, 32.38, 21.8 , 22.95,
       19.21, 17.25, 35.1 , 12.1 , 13.2 , 15.5 , 28.39, 33.01, 27.68,
       22.6 , 20.1 , 14.45, 21.78, 29.7 , 33.9 , 25.9 , 16.8 , 27.4 ,
       15.4 , 12.6 , 18.4 , 23.45, 31.87, 16.9 , 18.73, 24.97, 19.3 ,
       21.92, 13.5 , 15.3 , 14.  , 16.5 , 24.92, 13.6 , 36.12, 13.55,
       23.7 , 17.95, 23.3 , 29.41, 27.29, 30.98, 29.56, 14.35])

In [12]:
y_test

array([14. , 25. , 13. , 21. , 18. , 35. , 34.1, 20. , 15. , 23.5, 40.9,
       37.2, 18. , 23. , 15.5, 35.7, 31. , 27. , 18. , 37.3, 15.5, 23. ,
       24. , 18. , 34.5, 25.4, 36.1, 34. , 30. , 16. , 18.6, 37. , 15. ,
       33.5, 22.4, 24. , 19. , 16.9, 31.9, 12. , 14. , 15. , 27.4, 23.7,
       32. , 24. , 22.5, 16.5, 21. , 26. , 41.5, 29. , 15. , 30. , 15. ,
       10. , 18. , 20.2, 36. , 17. , 18. , 26.5, 18. , 22. , 12. , 14. ,
       15. , 18. , 23. , 14. , 32.3, 13. , 25. , 20. , 24. , 30.9, 26. ,
       32. , 24.5, 11. ])

In [13]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)

In [14]:
accuracy

0.8934475307243641

In [15]:
import pickle
pickle.dump(rf,open('regression.pkl','wb'))